"""SQL output: the module declares the table and the mapping, this writes it.

A module never builds a SQL string. It declares `sql_tables` (TableSpec) and
maps events to Rows; quoting, escaping, batching, DDL and dialect live here
alone.

DDL is emitted only for `managed` tables -- tables this toolkit owns. A table
that already exists in tw_world (creature_movement and friends) is declared
with managed=False and receives inserts only: handing the user a CREATE TABLE
for a table the server owns would be actively wrong.

Output is a reviewable file rather than a live connection, which is also what
this environment allows (no mysql client on PATH).
"""

from __future__ import annotations

import datetime as _dt
from pathlib import Path
from typing import Any, Iterable

from .. import log as _log
from ..core.contracts import Event, Row, SqlContext, TableSpec, offers_sql

_logger = _log.get_logger("emit.sql")

BATCH = 500

_INSERT_FORMS = {
    "mysql": {"plain": "INSERT INTO", "ignore": "INSERT IGNORE INTO", "replace": "REPLACE INTO"},
    "sqlite": {"plain": "INSERT INTO", "ignore": "INSERT OR IGNORE INTO",
               "replace": "INSERT OR REPLACE INTO"},
}


def literal(value: Any, dialect: str) -> str:
    """One SQL literal. The only place a value becomes text."""
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, (bytes, bytearray)):
        return f"0x{bytes(value).hex()}" if dialect == "mysql" else f"X'{bytes(value).hex()}'"
    text = str(value).replace("'", "''")
    if dialect == "mysql":
        text = text.replace("\\", "\\\\")
    return f"'{text}'"


def create_table(spec: TableSpec, dialect: str) -> str:
    cols = []
    for col in spec.columns:
        cols.append(f"  `{col.name}` {col.type}" + ("" if col.nullable else " NOT NULL"))
    if spec.key:
        cols.append("  PRIMARY KEY (" + ", ".join(f"`{k}`" for k in spec.key) + ")")
    suffix = " ENGINE=InnoDB DEFAULT CHARSET=utf8mb4" if dialect == "mysql" else ""
    comment = f"-- {spec.comment}\n" if spec.comment else ""
    return f"{comment}CREATE TABLE IF NOT EXISTS `{spec.name}` (\n" + ",\n".join(cols) + f"\n){suffix};\n"


class SqlSink:
    """Buffers rows per table, writes one .sql file on close."""

    def __init__(self, path: Path, capture_id: str, dialect: str = "mysql") -> None:
        self._path = path
        self._dialect = dialect
        self._ctx = SqlContext(capture_id=capture_id, dialect=dialect)
        self._specs: dict[str, TableSpec] = {}
        self._rows: dict[str, list[Row]] = {}
        self._unknown: set[str] = set()

    def handle(self, ev: Event, mod: Any) -> None:
        if not offers_sql(mod):
            return
        for spec in mod.sql_tables:
            self._specs.setdefault(spec.name, spec)
        for row in mod.sql_rows(ev, self._ctx):
            if row.table not in self._specs:
                if row.table not in self._unknown:
                    self._unknown.add(row.table)
                    _logger.error("module %s produced a row for undeclared table %r",
                                  mod.id, row.table)
                continue
            self._rows.setdefault(row.table, []).append(row)

    def close(self) -> None:
        total = sum(len(rows) for rows in self._rows.values())
        if not total:
            _logger.info("no SQL rows produced; %s not written", self._path)
            return
        self._path.parent.mkdir(parents=True, exist_ok=True)
        stamp = _dt.datetime.now().isoformat(timespec="seconds")
        with open(self._path, "w", encoding="utf-8", newline="\n") as fp:
            fp.write(f"-- generated by tortoise-capture-tools {stamp}\n")
            fp.write(f"-- capture: {self._ctx.capture_id}  dialect: {self._dialect}\n\n")
            for name, rows in self._rows.items():
                spec = self._specs[name]
                if spec.managed:
                    fp.write(create_table(spec, self._dialect) + "\n")
                else:
                    fp.write(f"-- `{name}` is an existing world table: inserts only, no DDL\n")
                fp.writelines(self._statements(spec, rows))
                fp.write("\n")
        _logger.info("wrote %d row(s) across %d table(s) to %s",
                     total, len(self._rows), self._path)

    def _statements(self, spec: TableSpec, rows: Iterable[Row]) -> Iterable[str]:
        form = _INSERT_FORMS[self._dialect].get(spec.conflict, "INSERT INTO")
        columns = ", ".join(f"`{c.name}`" for c in spec.columns)
        batch: list[str] = []
        rows = list(rows)
        for index, row in enumerate(rows, start=1):
            values = ", ".join(literal(row.values.get(c.name), self._dialect)
                               for c in spec.columns)
            batch.append(f"({values})")
            if len(batch) >= BATCH or index == len(rows):
                yield f"{form} `{spec.name}` ({columns}) VALUES\n" + ",\n".join(batch) + ";\n"
                batch = []
